---
- hosts: mongodb_cluster
  roles:
    - { role: mongodb_repos, tags: [ 'setup', 'packages' ] }
    - { role: mongodb_packages, tags: [ 'setup', 'packages' ] }
    - { role: mongodb_conf, tags: [ 'config' ] }
