---
- hosts: mongodb_cluster
  roles:
    - { role: galera_repos, tags: [ 'setup', 'packages' ] }
    - { role: galera_packages, tags: [ 'setup', 'packages' ] }
    - { role: galera_conf, tags: [ 'config' ] }
