---
- name: Add MongoDB Config configuration
  become: yes
  become_user: root
  template: src=mongodConfig.conf.j2 dest=/etc/mongod.conf
    owner=mongodb group=mongodb mode=0644
  when: inventory_hostname == groups['mongodb_cluster'][1]

- name: Add MongoDB Router configuration
  become: yes
  become_user: root
  template: src=mongos.conf.j2 dest=/etc/mongos.conf
    owner=mongodb group=mongodb mode=0644
  when: inventory_hostname == groups['mongodb_cluster'][0]

- name: Add MongoDB Router Systemd
  become: yes
  become_user: root
  template: src=mongos.service.j2 dest=/lib/systemd/system/mongos.service
    owner=mongodb group=mongodb mode=0644
  when: inventory_hostname == groups['mongodb_cluster'][0]

- name: Add MongoDB Shard configuration
  become: yes
  become_user: root
  template: src=mongodShard.conf.j2 dest=/etc/mongod.conf
    owner=mongodb group=mongodb mode=0644
  when: inventory_hostname == groups['mongodb_cluster'][2]
